// <auto-generated />
using System;
using BetaMaxRMS.DataUtility;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetaMaxRMS.Migrations
{
    [DbContext(typeof(BetaMaxDbContext))]
    partial class BetaMaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BetaMaxRMS.BetaMaxModels.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BetaMaxRMS.BetaMaxModels.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriceCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("BetaMaxRMS.BetaMaxModels.MovieRental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerRelation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DaysRented")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HandIn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieRelation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfZeroCostDays")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAmountPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MovieRental");
                });

            modelBuilder.Entity("BetaMaxRMS.BetaMaxModels.MovieRental", b =>
                {
                    b.HasOne("BetaMaxRMS.BetaMaxModels.Customer", null)
                        .WithMany("MovieRentals")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("BetaMaxRMS.BetaMaxModels.Customer", b =>
                {
                    b.Navigation("MovieRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
